spring:
  application:
    name: busanstamp

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/defaultdb?useSSL=true&requireSSL=true&sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: avnadmin
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.busanstamp
  configuration:
    map-underscore-to-camel-case: true

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

app:
  frontend-url: ${FRONTEND_URL}

qr:
  secret: ${QR_SECRET}

# 나중에 배포시 enabled=false 로 수정
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
